### ISSUE TITLE
Errors in ioBroker Logs When Using HQWidgets with "Show palette" in VIS-2 Editor and undefined (reading 'button')

### ISSUE THREAD

**Issue by jolichter** [ioBroker/ioBroker.vis-hqwidgets#67]
Hello, the hqwidgets are flooding my ioBroker logs with errors whenever I enable the "Show palette" option in the VIS-2 Editor. Despite this, my hqwidgets generally work as expected.

I understood that vis-hqwidgets should be compatible with vis-2 starting from version 1.3.0. Am I missing something, or is there a known issue?

My System Configuration:

- Node.js: 20.18.0
- NPM: 10.9.0
- js-controller: 7.03
- Admin: 7.1.4
- iobroker.ws: 6.2.5
- vis-2: 2.9.64
- vis-hqwidgets: 1.5.1

PS: Only pages using hqwidgets generate these errors in the log. I have checked user permissions and run `iob fix` as a precaution.

Here are my logs:

```
[pi4m@manjaro-arm ~]$ iob logs --watch
2024-12-07 14:58:46.435  - info: web.0 (1121) ==> Connected system.user.admin from ::ffff:192.168.1.45
2024-12-07 14:59:10.866  - error: web.0 (1121) can't render tplHqButton w000560 on "Start":
2024-12-07 14:59:10.871  - error: web.0 (1121) 0 - TypeError: Cannot read properties of undefined (reading 'button')TypeError: Cannot read properties of undefined (reading 'button')
2024-12-07 14:59:10.873  - error: web.0 (1121) 1 -     at Object.eval (tplHqButton.js:24:30)
2024-12-07 14:59:10.875  - error: web.0 (1121) 2 -     at n.render (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2229:46)
2024-12-07 14:59:10.877  - error: web.0 (1121) 3 -     at t.template.fn (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2223:26)
2024-12-07 14:59:10.879  - error: web.0 (1121) 4 -     at r (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1370:29)
2024-12-07 14:59:10.881  - error: web.0 (1121) 5 -     at Function.renderTo (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1449:63)
2024-12-07 14:59:10.884  - error: web.0 (1121) 6 -     at Function.renderAs (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1465:39)
2024-12-07 14:59:10.886  - error: web.0 (1121) 7 -     at e.view.e.template (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1401:47)
2024-12-07 14:59:10.890  - error: web.0 (1121) 8 -     at m.renderWidget (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:280724)
2024-12-07 14:59:10.895  - error: web.0 (1121) 9 -     at m.componentDidMount (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:260558)
2024-12-07 14:59:10.897  - error: web.0 (1121) 10 -     at xi (http://192.168.1.064:8082/vis-2/static/js/main.f305bc29.js:2:7595442)
2024-12-07 14:59:10.906  - error: web.0 (1121) can't render tplHqButton w000561 on "Start":
2024-12-07 14:59:10.908  - error: web.0 (1121) 0 - TypeError: Cannot read properties of undefined (reading 'button')TypeError: Cannot read properties of undefined (reading 'button')
2024-12-07 14:59:10.910  - error: web.0 (1121) 1 -     at Object.eval (tplHqButton.js:24:30)
2024-12-07 14:59:10.912  - error: web.0 (1121) 2 -     at n.render (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2229:46)
2024-12-07 14:59:10.914  - error: web.0 (1121) 3 -     at t.template.fn (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2223:26)
2024-12-07 14:59:10.917  - error: web.0 (1121) 4 -     at r (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1370:29)
2024-12-07 14:59:10.920  - error: web.0 (1121) 5 -     at Function.renderTo (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1449:63)
2024-12-07 14:59:10.921  - error: web.0 (1121) 6 -     at Function.renderAs (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1465:39)
2024-12-07 14:59:10.923  - error: web.0 (1121) 7 -     at e.view.e.template (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1401:47)
2024-12-07 14:59:10.925  - error: web.0 (1121) 8 -     at m.renderWidget (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:280724)
2024-12-07 14:59:10.927  - error: web.0 (1121) 9 -     at m.componentDidMount (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:260558)
2024-12-07 14:59:10.929  - error: web.0 (1121) 10 -     at xi (http://192.168.1.064:8082/vis-2/static/js/main.f305bc29.js:2:7595442)
2024-12-07 14:59:10.940  - error: web.0 (1121) can't render tplHqButton w000562 on "Start":
2024-12-07 14:59:10.944  - error: web.0 (1121) 0 - TypeError: Cannot read properties of undefined (reading 'button')TypeError: Cannot read properties of undefined (reading 'button')
2024-12-07 14:59:10.946  - error: web.0 (1121) 1 -     at Object.eval (tplHqButton.js:24:30)
2024-12-07 14:59:10.949  - error: web.0 (1121) 2 -     at n.render (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2229:46)
2024-12-07 14:59:10.954  - error: web.0 (1121) 3 -     at t.template.fn (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2223:26)
2024-12-07 14:59:10.958  - error: web.0 (1121) 4 -     at r (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1370:29)
2024-12-07 14:59:10.963  - error: web.0 (1121) 5 -     at Function.renderTo (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1449:63)
2024-12-07 14:59:10.965  - error: web.0 (1121) 6 -     at Function.renderAs (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1465:39)
2024-12-07 14:59:10.967  - error: web.0 (1121) 7 -     at e.view.e.template (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1401:47)
2024-12-07 14:59:10.973  - error: web.0 (1121) 8 -     at m.renderWidget (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:280724)
2024-12-07 14:59:10.977  - error: web.0 (1121) 9 -     at m.componentDidMount (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:260558)
2024-12-07 14:59:10.980  - error: web.0 (1121) 10 -     at xi (http://192.168.1.064:8082/vis-2/static/js/main.f305bc29.js:2:7595442)
2024-12-07 14:59:10.990  - error: web.0 (1121) can't render tplHqButton w000563 on "Start":
2024-12-07 14:59:10.994  - error: web.0 (1121) 0 - TypeError: Cannot read properties of undefined (reading 'button')TypeError: Cannot read properties of undefined (reading 'button')
2024-12-07 14:59:10.997  - error: web.0 (1121) 1 -     at Object.eval (tplHqButton.js:24:30)
2024-12-07 14:59:10.998  - error: web.0 (1121) 2 -     at n.render (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2229:46)
2024-12-07 14:59:11.000  - error: web.0 (1121) 3 -     at t.template.fn (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2223:26)
2024-12-07 14:59:11.001  - error: web.0 (1121) 4 -     at r (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1370:29)
2024-12-07 14:59:11.004  - error: web.0 (1121) 5 -     at Function.renderTo (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1449:63)
2024-12-07 14:59:11.006  - error: web.0 (1121) 6 -     at Function.renderAs (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1465:39)
2024-12-07 14:59:11.007  - error: web.0 (1121) 7 -     at e.view.e.template (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1401:47)
2024-12-07 14:59:11.009  - error: web.0 (1121) 8 -     at m.renderWidget (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:280724)
2024-12-07 14:59:11.010  - error: web.0 (1121) 9 -     at m.componentDidMount (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:260558)
2024-12-07 14:59:11.012  - error: web.0 (1121) 10 -     at xi (http://192.168.1.064:8082/vis-2/static/js/main.f305bc29.js:2:7595442)
2024-12-07 14:59:11.025  - error: web.0 (1121) can't render tplHqButton w000564 on "Start":
2024-12-07 14:59:11.028  - error: web.0 (1121) 0 - TypeError: Cannot read properties of undefined (reading 'button')TypeError: Cannot read properties of undefined (reading 'button')
2024-12-07 14:59:11.030  - error: web.0 (1121) 1 -     at Object.eval (tplHqButton.js:24:30)
2024-12-07 14:59:11.032  - error: web.0 (1121) 2 -     at n.render (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2229:46)
2024-12-07 14:59:11.034  - error: web.0 (1121) 3 -     at t.template.fn (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2223:26)
2024-12-07 14:59:11.035  - error: web.0 (1121) 4 -     at r (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1370:29)
2024-12-07 14:59:11.037  - error: web.0 (1121) 5 -     at Function.renderTo (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1449:63)
2024-12-07 14:59:11.039  - error: web.0 (1121) 6 -     at Function.renderAs (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1465:39)
2024-12-07 14:59:11.041  - error: web.0 (1121) 7 -     at e.view.e.template (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1401:47)
2024-12-07 14:59:11.042  - error: web.0 (1121) 8 -     at m.renderWidget (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:280724)
2024-12-07 14:59:11.044  - error: web.0 (1121) 9 -     at m.componentDidMount (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:260558)
2024-12-07 14:59:11.046  - error: web.0 (1121) 10 -     at xi (http://192.168.1.064:8082/vis-2/static/js/main.f305bc29.js:2:7595442)
2024-12-07 14:59:11.052  - error: web.0 (1121) can't render tplHqButton w000565 on "Start":
2024-12-07 14:59:11.055  - error: web.0 (1121) 0 - TypeError: Cannot read properties of undefined (reading 'button')TypeError: Cannot read properties of undefined (reading 'button')
2024-12-07 14:59:11.056  - error: web.0 (1121) 1 -     at Object.eval (tplHqButton.js:24:30)
2024-12-07 14:59:11.058  - error: web.0 (1121) 2 -     at n.render (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2229:46)
2024-12-07 14:59:11.059  - error: web.0 (1121) 3 -     at t.template.fn (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2223:26)
2024-12-07 14:59:11.061  - error: web.0 (1121) 4 -     at r (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1370:29)
2024-12-07 14:59:11.062  - error: web.0 (1121) 5 -     at Function.renderTo (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1449:63)
2024-12-07 14:59:11.064  - error: web.0 (1121) 6 -     at Function.renderAs (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1465:39)
2024-12-07 14:59:11.065  - error: web.0 (1121) 7 -     at e.view.e.template (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1401:47)
2024-12-07 14:59:11.067  - error: web.0 (1121) 8 -     at m.renderWidget (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:280724)
2024-12-07 14:59:11.073  - error: web.0 (1121) 9 -     at m.componentDidMount (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:260558)
2024-12-07 14:59:11.083  - error: web.0 (1121) 10 -     at xi (http://192.168.1.064:8082/vis-2/static/js/main.f305bc29.js:2:7595442)
2024-12-07 14:59:11.098  - error: web.0 (1121) can't render tplHqButton w000570 on "Start":
2024-12-07 14:59:11.100  - error: web.0 (1121) 0 - TypeError: Cannot read properties of undefined (reading 'button')TypeError: Cannot read properties of undefined (reading 'button')
2024-12-07 14:59:11.103  - error: web.0 (1121) 1 -     at Object.eval (tplHqButton.js:24:30)
2024-12-07 14:59:11.109  - error: web.0 (1121) 2 -     at n.render (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2229:46)
2024-12-07 14:59:11.114  - error: web.0 (1121) 3 -     at t.template.fn (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2223:26)
2024-12-07 14:59:11.116  - error: web.0 (1121) 4 -     at r (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1370:29)
2024-12-07 14:59:11.118  - error: web.0 (1121) 5 -     at Function.renderTo (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1449:63)
2024-12-07 14:59:11.120  - error: web.0 (1121) 6 -     at Function.renderAs (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1465:39)
2024-12-07 14:59:11.123  - error: web.0 (1121) 7 -     at e.view.e.template (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1401:47)
2024-12-07 14:59:11.125  - error: web.0 (1121) 8 -     at m.renderWidget (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:280724)
2024-12-07 14:59:11.126  - error: web.0 (1121) 9 -     at m.componentDidMount (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:260558)
2024-12-07 14:59:11.134  - error: web.0 (1121) 10 -     at xi (http://192.168.1.064:8082/vis-2/static/js/main.f305bc29.js:2:7595442)
2024-12-07 14:59:11.145  - error: web.0 (1121) can't render tplHqDoor w000588 on "Start":
2024-12-07 14:59:11.150  - error: web.0 (1121) 0 - TypeError: Cannot read properties of undefined (reading 'door')TypeError: Cannot read properties of undefined (reading 'door')
2024-12-07 14:59:11.152  - error: web.0 (1121) 1 -     at Object.eval (tplHqDoor.js:24:29)
2024-12-07 14:59:11.154  - error: web.0 (1121) 2 -     at n.render (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2229:46)
2024-12-07 14:59:11.157  - error: web.0 (1121) 3 -     at t.template.fn (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2223:26)
2024-12-07 14:59:11.160  - error: web.0 (1121) 4 -     at r (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1370:29)
2024-12-07 14:59:11.162  - error: web.0 (1121) 5 -     at Function.renderTo (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1449:63)
2024-12-07 14:59:11.164  - error: web.0 (1121) 6 -     at Function.renderAs (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1465:39)
2024-12-07 14:59:11.166  - error: web.0 (1121) 7 -     at e.view.e.template (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1401:47)
2024-12-07 14:59:11.168  - error: web.0 (1121) 8 -     at m.renderWidget (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:280724)
2024-12-07 14:59:11.173  - error: web.0 (1121) 9 -     at m.componentDidMount (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:260558)
2024-12-07 14:59:11.176  - error: web.0 (1121) 10 -     at xi (http://192.168.1.064:8082/vis-2/static/js/main.f305bc29.js:2:7595442)
2024-12-07 14:59:11.181  - error: web.0 (1121) can't render tplHqDoor w000589 on "Start":
2024-12-07 14:59:11.187  - error: web.0 (1121) 0 - TypeError: Cannot read properties of undefined (reading 'door')TypeError: Cannot read properties of undefined (reading 'door')
2024-12-07 14:59:11.190  - error: web.0 (1121) 1 -     at Object.eval (tplHqDoor.js:24:29)
2024-12-07 14:59:11.192  - error: web.0 (1121) 2 -     at n.render (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2229:46)
2024-12-07 14:59:11.194  - error: web.0 (1121) 3 -     at t.template.fn (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2223:26)
2024-12-07 14:59:11.196  - error: web.0 (1121) 4 -     at r (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1370:29)
2024-12-07 14:59:11.198  - error: web.0 (1121) 5 -     at Function.renderTo (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1449:63)
2024-12-07 14:59:11.200  - error: web.0 (1121) 6 -     at Function.renderAs (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1465:39)
2024-12-07 14:59:11.203  - error: web.0 (1121) 7 -     at e.view.e.template (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1401:47)
2024-12-07 14:59:11.205  - error: web.0 (1121) 8 -     at m.renderWidget (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:280724)
2024-12-07 14:59:11.207  - error: web.0 (1121) 9 -     at m.componentDidMount (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:260558)
2024-12-07 14:59:11.208  - error: web.0 (1121) 10 -     at xi (http://192.168.1.064:8082/vis-2/static/js/main.f305bc29.js:2:7595442)
2024-12-07 14:59:11.222  - error: web.0 (1121) can't render tplHqDoor w000599 on "Start":
2024-12-07 14:59:11.224  - error: web.0 (1121) 0 - TypeError: Cannot read properties of undefined (reading 'door')TypeError: Cannot read properties of undefined (reading 'door')
2024-12-07 14:59:11.226  - error: web.0 (1121) 1 -     at Object.eval (tplHqDoor.js:24:29)
2024-12-07 14:59:11.227  - error: web.0 (1121) 2 -     at n.render (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2229:46)
2024-12-07 14:59:11.229  - error: web.0 (1121) 3 -     at t.template.fn (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2223:26)
2024-12-07 14:59:11.230  - error: web.0 (1121) 4 -     at r (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1370:29)
2024-12-07 14:59:11.232  - error: web.0 (1121) 5 -     at Function.renderTo (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1449:63)
2024-12-07 14:59:11.235  - error: web.0 (1121) 6 -     at Function.renderAs (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1465:39)
2024-12-07 14:59:11.238  - error: web.0 (1121) 7 -     at e.view.e.template (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1401:47)
2024-12-07 14:59:11.244  - error: web.0 (1121) 8 -     at m.renderWidget (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:280724)
2024-12-07 14:59:11.249  - error: web.0 (1121) 9 -     at m.componentDidMount (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:260558)
2024-12-07 14:59:11.253  - error: web.0 (1121) 10 -     at xi (http://192.168.1.064:8082/vis-2/static/js/main.f305bc29.js:2:7595442)
2024-12-07 14:59:11.269  - error: web.0 (1121) can't render tplHqButton w000606 on "Start":
2024-12-07 14:59:11.271  - error: web.0 (1121) 0 - TypeError: Cannot read properties of undefined (reading 'button')TypeError: Cannot read properties of undefined (reading 'button')
2024-12-07 14:59:11.273  - error: web.0 (1121) 1 -     at Object.eval (tplHqButton.js:24:30)
2024-12-07 14:59:11.275  - error: web.0 (1121) 2 -     at n.render (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2229:46)
2024-12-07 14:59:11.276  - error: web.0 (1121) 3 -     at t.template.fn (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2223:26)
2024-12-07 14:59:11.278  - error: web.0 (1121) 4 -     at r (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1370:29)
2024-12-07 14:59:11.280  - error: web.0 (1121) 5 -     at Function.renderTo (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1449:63)
2024-12-07 14:59:11.282  - error: web.0 (1121) 6 -     at Function.renderAs (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1465:39)
2024-12-07 14:59:11.283  - error: web.0 (1121) 7 -     at e.view.e.template (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1401:47)
2024-12-07 14:59:11.285  - error: web.0 (1121) 8 -     at m.renderWidget (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:280724)
2024-12-07 14:59:11.287  - error: web.0 (1121) 9 -     at m.componentDidMount (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:260558)
2024-12-07 14:59:11.290  - error: web.0 (1121) 10 -     at xi (http://192.168.1.064:8082/vis-2/static/js/main.f305bc29.js:2:7595442)
2024-12-07 14:59:11.313  - error: web.0 (1121) can't render tplHqCircle w000618 on "Start":
2024-12-07 14:59:11.317  - error: web.0 (1121) 0 - TypeError: Cannot read properties of undefined (reading 'circle')TypeError: Cannot read properties of undefined (reading 'circle')
2024-12-07 14:59:11.319  - error: web.0 (1121) 1 -     at Object.eval (tplHqCircle.js:24:29)
2024-12-07 14:59:11.321  - error: web.0 (1121) 2 -     at n.render (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2229:46)
2024-12-07 14:59:11.322  - error: web.0 (1121) 3 -     at t.template.fn (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2223:26)
2024-12-07 14:59:11.323  - error: web.0 (1121) 4 -     at r (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1370:29)
2024-12-07 14:59:11.326  - error: web.0 (1121) 5 -     at Function.renderTo (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1449:63)
2024-12-07 14:59:11.329  - error: web.0 (1121) 6 -     at Function.renderAs (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1465:39)
2024-12-07 14:59:11.333  - error: web.0 (1121) 7 -     at e.view.e.template (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1401:47)
2024-12-07 14:59:11.336  - error: web.0 (1121) 8 -     at m.renderWidget (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:280724)
2024-12-07 14:59:11.338  - error: web.0 (1121) 9 -     at m.componentDidMount (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:260558)
2024-12-07 14:59:11.340  - error: web.0 (1121) 10 -     at xi (http://192.168.1.064:8082/vis-2/static/js/main.f305bc29.js:2:7595442)
2024-12-07 14:59:11.350  - error: web.0 (1121) can't render tplHqButton w000619 on "Start":
2024-12-07 14:59:11.352  - error: web.0 (1121) 0 - TypeError: Cannot read properties of undefined (reading 'button')TypeError: Cannot read properties of undefined (reading 'button')
2024-12-07 14:59:11.354  - error: web.0 (1121) 1 -     at Object.eval (tplHqButton.js:24:30)
2024-12-07 14:59:11.356  - error: web.0 (1121) 2 -     at n.render (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2229:46)
2024-12-07 14:59:11.359  - error: web.0 (1121) 3 -     at t.template.fn (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2223:26)
2024-12-07 14:59:11.362  - error: web.0 (1121) 4 -     at r (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1370:29)
2024-12-07 14:59:11.364  - error: web.0 (1121) 5 -     at Function.renderTo (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1449:63)
2024-12-07 14:59:11.366  - error: web.0 (1121) 6 -     at Function.renderAs (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1465:39)
2024-12-07 14:59:11.368  - error: web.0 (1121) 7 -     at e.view.e.template (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1401:47)
2024-12-07 14:59:11.371  - error: web.0 (1121) 8 -     at m.renderWidget (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:280724)
2024-12-07 14:59:11.374  - error: web.0 (1121) 9 -     at m.componentDidMount (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:260558)
2024-12-07 14:59:11.376  - error: web.0 (1121) 10 -     at xi (http://192.168.1.064:8082/vis-2/static/js/main.f305bc29.js:2:7595442)
2024-12-07 14:59:11.451  - error: web.0 (1121) can't render tplHqLock w000678 on "Start":
2024-12-07 14:59:11.453  - error: web.0 (1121) 0 - TypeError: Cannot read properties of undefined (reading 'lock')TypeError: Cannot read properties of undefined (reading 'lock')
2024-12-07 14:59:11.454  - error: web.0 (1121) 1 -     at Object.eval (tplHqLock.js:24:29)
2024-12-07 14:59:11.456  - error: web.0 (1121) 2 -     at n.render (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2229:46)
2024-12-07 14:59:11.457  - error: web.0 (1121) 3 -     at t.template.fn (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2223:26)
2024-12-07 14:59:11.459  - error: web.0 (1121) 4 -     at r (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1370:29)
2024-12-07 14:59:11.461  - error: web.0 (1121) 5 -     at Function.renderTo (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1449:63)
2024-12-07 14:59:11.462  - error: web.0 (1121) 6 -     at Function.renderAs (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1465:39)
2024-12-07 14:59:11.464  - error: web.0 (1121) 7 -     at e.view.e.template (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1401:47)
2024-12-07 14:59:11.465  - error: web.0 (1121) 8 -     at m.renderWidget (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:280724)
2024-12-07 14:59:11.467  - error: web.0 (1121) 9 -     at m.componentDidMount (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:260558)
2024-12-07 14:59:11.470  - error: web.0 (1121) 10 -     at xi (http://192.168.1.064:8082/vis-2/static/js/main.f305bc29.js:2:7595442)
2024-12-07 14:59:11.488  - error: web.0 (1121) can't render tplHqButton w000696 on "Start":
2024-12-07 14:59:11.490  - error: web.0 (1121) 0 - TypeError: Cannot read properties of undefined (reading 'button')TypeError: Cannot read properties of undefined (reading 'button')
2024-12-07 14:59:11.492  - error: web.0 (1121) 1 -     at Object.eval (tplHqButton.js:24:30)
2024-12-07 14:59:11.493  - error: web.0 (1121) 2 -     at n.render (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2229:46)
2024-12-07 14:59:11.495  - error: web.0 (1121) 3 -     at t.template.fn (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:2223:26)
2024-12-07 14:59:11.496  - error: web.0 (1121) 4 -     at r (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1370:29)
2024-12-07 14:59:11.498  - error: web.0 (1121) 5 -     at Function.renderTo (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1449:63)
2024-12-07 14:59:11.499  - error: web.0 (1121) 6 -     at Function.renderAs (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1465:39)
2024-12-07 14:59:11.501  - error: web.0 (1121) 7 -     at e.view.e.template (http://192.168.1.064:8082/vis-2/lib/js/can.custom.js:1401:47)
2024-12-07 14:59:11.503  - error: web.0 (1121) 8 -     at m.renderWidget (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:280724)
2024-12-07 14:59:11.505  - error: web.0 (1121) 9 -     at m.componentDidMount (http://192.168.1.064:8082/vis-2/static/js/143.59aaad96.chunk.js:1:260558)
2024-12-07 14:59:11.516  - error: web.0 (1121) 10 -     at xi (http://192.168.1.064:8082/vis-2/static/js/main.f305bc29.js:2:7595442)
```

Thanks!

**Comment by jolichter** [comment]
I reproduced the scenario on my test Pi4 with the same configuration and a new VIS-2 page (tablet_backup) and created a video including the console view. In this example, the hqwidgets Dimmer Icon is only displayed as a dot in the VIS-2 interface because it cannot be rendered. The log indicates an issue with the tplHqButton component in VIS-2 (TypeError), as it attempts to access an undefined `button` property.

The error occurs exclusively with vis-hqwidgets when the palette view is enabled.
Video: [testPi4_vis2_video.webm](https://github.com/user-attachments/assets/95f3ee8f-d766-466f-b355-f9c76499b309)

Sorry, I also posted my concern with a link to this thread in the German forum ([Link](https://forum.iobroker.net/topic/78522/vis-2-mit-vis-hqwidgets)).

**Comment by jolichter** [comment]
Since no one has confirmed this issue after six weeks, I assume it only affects me. I will close the issue as I no longer use the widget, and the error has not occurred again.

**Comment by jolichter** [comment]
Since no one has confirmed this issue after six weeks, I assume it only affects me. I will close the issue as I no longer use the widget, and the error has not occurred again.
